// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// Stellt die Firebase-Konfigurationsoptionen für alle unterstützten Plattformen bereit.
///
/// Diese Klasse wird automatisch von der FlutterFire CLI generiert und sollte nicht manuell geändert werden.
/// Sie ermöglicht die Initialisierung von Firebase mit den korrekten Optionen je nach Plattform.
class DefaultFirebaseOptions {
  /// Gibt die passenden [FirebaseOptions] für die aktuelle Plattform zurück.
  ///
  /// Wird von `Firebase.initializeApp` verwendet.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been konfiguriert für Linux - '
          'bitte führe die FlutterFire CLI erneut aus, um dies zu konfigurieren.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions werden für diese Plattform nicht unterstützt.',
        );
    }
  }

  /// Firebase-Konfiguration für Web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOkeYmHmO-SDTAJ7nvbRdDvqoLcd229o0',
    appId: '1:767015238873:web:a8aecf547a9e30b86dd2c8',
    messagingSenderId: '767015238873',
    projectId: 'sommersprossenapp',
    authDomain: 'sommersprossenapp.firebaseapp.com',
    storageBucket: 'sommersprossenapp.firebasestorage.app',
  );

  /// Firebase-Konfiguration für Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjfAOsqknsytG797iR7DzFW0nSnkpgHc',
    appId: '1:767015238873:android:2129128619159e886dd2c8',
    messagingSenderId: '767015238873',
    projectId: 'sommersprossenapp',
    storageBucket: 'sommersprossenapp.firebasestorage.app',
  );

  /// Firebase-Konfiguration für iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACbqmzruEOzcGJeKqDRYro6ZzmMBXk8M',
    appId: '1:767015238873:ios:9275b33ef5c6ef936dd2c8',
    messagingSenderId: '767015238873',
    projectId: 'sommersprossenapp',
    storageBucket: 'sommersprossenapp.firebasestorage.app',
    iosBundleId: 'com.example.sommersprossenApp',
  );

  /// Firebase-Konfiguration für macOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAACbqmzruEOzcGJeKqDRYro6ZzmMBXk8M',
    appId: '1:767015238873:ios:9275b33ef5c6ef936dd2c8',
    messagingSenderId: '767015238873',
    projectId: 'sommersprossenapp',
    storageBucket: 'sommersprossenapp.firebasestorage.app',
    iosBundleId: 'com.example.sommersprossenApp',
  );

  /// Firebase-Konfiguration für Windows.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkeYmHmO-SDTAJ7nvbRdDvqoLcd229o0',
    appId: '1:767015238873:web:a8aecf547a9e30b86dd2c8',
    messagingSenderId: '767015238873',
    projectId: 'sommersprossenapp',
    authDomain: 'sommersprossenapp.firebaseapp.com',
    storageBucket: 'sommersprossenapp.firebasestorage.app',
  );
}
